
# taken from: https://stackoverflow.com/questions/45840664/installing-nodejs-lts-for-ansible

- name: "add gpg key for nodejs"
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
  become: yes
- name: "add nodejs repos"
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ nodejs_version }}.x {{ ansible_facts.distribution_release }} main"
  become: yes
- name: "install nodejs"
  apt:
    name: nodejs
    state: present
  become: yes